#!/usr/bin/env python
#usage:
# python beken_packager_wrapper -i $(CFG_SOC_NAME) -s $(CFG_FLASH_SELECTION_TYPE)

import os
import sys
import json
import shutil
import argparse



out_json_2M = {
    "magic": "RT-Thread",
    "version": "0.1",
    "count": 2,
    "section": [
        {
            "firmware": "bootloader_bk7231n_uart2_v1.0.12.bin",
            "version": "2M.1220",
            "partition": "bootloader",
            "start_addr": "0x00000000",
            "size": "65280"
        },
        {
            "firmware": "../../out/bk7231_bsp.bin",
            "version": "2M.1220",
            "partition": "app",
            "start_addr": "0x00011000",
            "size": "1156K"
        }
    ]
}

out_json = out_json_2M
out_json["section"][0]["firmware"] = bootloader_str
out_json["section"][1]["firmware"] = firmware_str
out_json = json.dumps(out_json, sort_keys=True, indent=4)


with open(str(out_path), "w") as f:
    f.write(out_json)

if os.name == 'nt':
    os.system("beken_packager {}".format(out_path))
else:
    os.system("./beken_packager {}".format(out_path))
#copy all_2M.1220.bin as default for tools/script/build_include.sh
shutil.copy(full_image_old, "../../out/" + full_image_old)
shutil.move(full_image_old, "../../out/" + full_image_new)
shutil.move(uart_image_old, "../../out/" + uart_image_new)
shutil.copy(bootloader_str, "../../out/" + bootloader_str)
os.remove(out_path)
